# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Using the latest stable version
    hooks:
      - id: check-yaml

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.1 # Replacing with latest stable version
    hooks:
      - id: pylint

        additional_dependencies: # Ensures additional dependencies are installed
            - numpy
            - pytest
            - flask
            - werkzeug
            - Pillow
            - keras==2.13.1
            - tensorflow==2.13.1
